/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddOnsSlugRouteImport } from './routes/add-ons.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddOnsSlugRoute = AddOnsSlugRouteImport.update({
  id: '/add-ons/$slug',
  path: '/add-ons/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-ons/$slug': typeof AddOnsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-ons/$slug': typeof AddOnsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-ons/$slug': typeof AddOnsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-ons/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-ons/$slug'
  id: '__root__' | '/' | '/add-ons/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddOnsSlugRoute: typeof AddOnsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-ons/$slug': {
      id: '/add-ons/$slug'
      path: '/add-ons/$slug'
      fullPath: '/add-ons/$slug'
      preLoaderRoute: typeof AddOnsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddOnsSlugRoute: AddOnsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
